### ISSUE TITLE
Weirdly placed transparent pixels in decompressed Ultra Despair Girl GXT conversions

### ISSUE THREAD

**Issue by internetakias** [xdanieldzd/GXTConvert#3]
![bg_street01pic00 texture 0](https://cloud.githubusercontent.com/assets/5077063/15168751/fddb4af0-173c-11e6-9745-e2d543f04dbd.png)
Original files:
[bg_street01pic00.zip](https://github.com/xdanieldzd/GXTConvert/files/258496/bg_street01pic00.zip)

**Comment by xdanieldzd** [comment]
That specific file uses compressed DXT1 image data, which I had assumed to be in RGBA mode (based on what DXT1/UBC1's entry in SceGxmTextureFormat might imply, and the OpenGL COMPRESSED_RGBA_S3TC_DXT1_EXT specs). This assumption appears to be incorrect and the Vita's DXT1 data is RGB-only, which, when treated according to the aforementioned RGB**A** mode specs, caused transparent pixels to appear where they shouldn't.

I have removed the RGBA support from GXTConvert's DXT1 code in commit 6b0ec70, which _should_ fix this issue for this and any other DXT1/UBC1-format GXTs with incorrect transparent pixels.
