### ISSUE TITLE
Works, but looks like not fully for this gtx from psv

### ISSUE THREAD

**Issue by Makein** [xdanieldzd/GXTConvert#6]
https://mega.nz/#!f0djwT6T!1lgAm7MT1x7RIX6xJdRfHhOwNYEWvZLtl_qV50cB4Gw
Can you look and help? It gets 1 texture, but i think that it's have more than 1 in 1 file

**Comment by xdanieldzd** [comment]
Sorry, but judging from their GXT headers, it looks like these files all do only contain a single texture each.

If you want to follow along, the value at offset 0x08 in a GXT file holds the number of textures contained within, which is 0x00000001 in every file in the archive (mind the byte order).

Next, at offset 0x0C and 0x10 you have the offset and size of the texture data - for each of your files, they're 0x00000040 and 0x00040400 respectively, and if you check the actual size of each file, you'll see that it's these two values added together (i.e. 0x00040440).

So, no, as best as I can tell, GXTConvert is working correctly.

**Comment by Makein** [comment]
Yeap, works perfect sorry...
Looks i cant unpack cpk right, because in it files have the same names
And they overwrite each other when unpacked

**Comment by xdanieldzd** [comment]
No problem, and I sadly haven't found a "perfect" CPK unpacker yet, either (nor do I think I'd be able to write one), so I can't help you with that, sorry.

**Comment by Makein** [comment]
No worries, because you do gtx to png converter)
Oh, looks like Noesis can do that thing too Oo
